"""Introduce User, Account, Payment models and insert test admin/user.

Revision ID: 0fa9a2f00aeb
Revises: bcedf426a7dc
Create Date: 2026-05-31 18:13:55.194709

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import BigInteger, Boolean, Numeric, String
from sqlalchemy.sql import column, table

from app.services.auth import PasswordHelper

# revision identifiers, used by Alembic.
revision: str = "0fa9a2f00aeb"
down_revision: str | Sequence[str] | None = "bcedf426a7dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(
        op.f("ix_payments_transaction_id"), "payments", ["transaction_id"], unique=True
    )

    password_helper = PasswordHelper()

    users_table = sa.table(
        "users",
        sa.column("id", BigInteger),
        column("email", String),
        column("hashed_password", String),
        column("full_name", String),
        column("is_admin", Boolean),
    )
    test_users = [
        {
            "id": 1,
            "email": "client1@example.com",
            "hashed_password": password_helper.hash("clientpass"),
            "full_name": "Test Client",
            "is_admin": False,
        },
        {
            "id": 2,
            "email": "admin1@example.com",
            "hashed_password": password_helper.hash("adminpass"),
            "full_name": "Test Admin",
            "is_admin": True,
        },
    ]
    op.bulk_insert(users_table, test_users)

    accounts_table = table(
        "accounts",
        column("id", sa.Integer),
        column("user_id", BigInteger),
        column("balance", Numeric(12, 2)),
    )
    op.bulk_insert(
        accounts_table,
        [
            {"id": 1, "user_id": 1, "balance": 0.00},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_transaction_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
